Book dto
Nikname2303/book-store pull request #2
Opened 2024-04-23 12:13 UTC by Nikname2303

2024-04-23 14:48 UTC, JohnGrey17 reviewed
Looks good for me added minor suggestion

2024-04-23 14:48 UTC, JohnGrey17 commented on src/main/java/com/example/bookshop/dto/BookDto.java
> +
maybe will be better to use separate annotation as @Getter @Setter @ToString ect

2024-04-23 14:48 UTC, JohnGrey17 commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +
same here

2024-04-23 15:14 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-04-23 15:14 UTC, andrii-hoienko commented on pom.xml
> +			<version>1.18.32</version>
Better to create properties for all versions

2024-04-23 15:14 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/controller/BookController.java
> +@RequestMapping("/books")
```suggestion
@RequestMapping("api/books")
```

2024-04-23 15:14 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/dto/BookDto.java
> +
```suggestion
```

2024-04-23 15:14 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/repository/impl/BookRepositoryImpl.java
> +        try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
Please add catch

2024-04-24 07:53 UTC, karma-o commented on src/main/java/com/example/bookshop/repository/impl/BookRepositoryImpl.java
> +        } catch (RuntimeException e) {
```suggestion
        } catch (Exception e) {
```
Just to be sure we won't miss anything

2024-04-24 07:53 UTC, karma-o commented on pom.xml
> +		</dependency>
why did you remove the specified version? Andrii said that we should just move it to property(variable) as you did with other dependencies like mapstruct

2024-04-24 12:18 UTC, merged