replaced bookrepository with jparepository, added Liquibase support a…
Nikname2303/book-store pull request #3
Opened 2024-04-26 11:55 UTC by Nikname2303

…nd implemented soft delete

2024-04-26 15:17 UTC, fedaktaras commented on src/main/java/com/example/bookshop/controller/BookController.java
PUT: /api/books/{id} (Update a specific book) 
Update required

2024-04-26 15:27 UTC, fedaktaras commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
Update required

2024-04-26 17:43 UTC, ValentynSharshon requested changes
Good job, but the task is not fully completed.

2024-04-26 17:43 UTC, ValentynSharshon commented on src/main/resources/liquibase.properties
> +password=MySQL1234
As I know, it's bad practice to pass the login and password to connect to the database in the configuration files.

2024-04-26 17:43 UTC, ValentynSharshon commented on src/main/resources/application.properties
>  spring.datasource.password=MySQL1234
As I know, it's bad practice to pass the login and password to connect to the database in the configuration files.

2024-04-26 17:43 UTC, ValentynSharshon commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
I agree with Taras.

2024-04-29 10:42 UTC, yevheniisynytsia requested changes

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +        Optional<Book> optionalBook = bookRepository.findById(id);
use orElseThrow()

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +                book.setAuthor(requestDto.getAuthor());
let's remove these checks. We will add validation in the next HW. For now it is ok to remove those

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/application.properties
>  spring.datasource.password=MySQL1234
It is not very good to push those to github. Bad habit

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
```

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
primaryKey is not nullable by default

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-column-isDeleted-to-books-table.yaml
> +                  type: BIT
```suggestion
                  type: boolean
```

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-column-isDeleted-to-books-table.yaml
> +                  type: BIT
and add default value false

2024-04-29 10:42 UTC, yevheniisynytsia commented on src/main/resources/liquibase.properties
> +url=jdbc:mysql://localhost:3306/book_shop
liquibase should work without it by default

2024-04-29 12:19 UTC, Nikname2303 commented on src/main/resources/db/changelog/changes/02-add-column-isDeleted-to-books-table.yaml
> +                  type: BIT
Doesn`t work with boolean or BOOLEAN, make tinyint(1)

2024-04-29 13:45 UTC, andrii-hoienko approved these changes
Nice

2024-04-30 06:24 UTC, merged