Added CustomGlobalExceptionHandler and validate logic for RequestDto
Nikname2303/book-store pull request #4
Opened 2024-04-30 13:29 UTC by Nikname2303

2024-04-30 18:19 UTC, VolandevlodD requested changes
LGTM `(*/ω＼*)`
Left some suggestions)

2024-04-30 18:19 UTC, VolandevlodD commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @NotNull
I believe it`s better to use the `@NotBlank` constraint for a string in general and in this case especially.
**[baeldung](https://www.baeldung.com/java-bean-validation-not-null-empty-blank)**

2024-04-30 18:19 UTC, VolandevlodD commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @Min(0)
Here also, we can use the `@PositiveOrZero` constraint since it is applicable for BigDecimals.

2024-04-30 18:19 UTC, VolandevlodD commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +        }
```suggestion
     if (e instanceof FieldError fieldError) {
            String field = fieldError.getField();
            String message = fieldError.getDefaultMessage();
            return String.format("%s: %s", field, message);
        }
```
[Here u can find out why](https://mate.academy/learn/java-spring-boot/java-spring-boot-globalexceptionhandler/linear?section=theory&testTaskSlug=java_globalexceptionhandler_and_data_validation&theoryId=2722#%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D1%83-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%B2%D0%B0%D1%87%D0%B0)

2024-05-02 10:13 UTC, yevheniisynytsia requested changes

2024-05-02 10:13 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @NotBlank
please add `@ISBN`
https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ISBN.html

2024-05-02 10:13 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +
I believe your app throws some exceptions. Let's handle them as well
Like `EntityNotFound`, `DataIntegrityViolationException`, or general `Exception`

2024-05-02 13:53 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-02 13:53 UTC, andrii-hoienko commented on pom.xml
> +		</dependency>
Why this is required?

2024-05-02 13:53 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +}
Public methods should go first

2024-05-02 13:53 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +                .body(exception.getMessage());
Is it possible to make generic error response with timestamp field like you did in handleMethodArgumentNotValid

2024-05-02 13:53 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +        return bookRepository.findAll(pageable).stream()
I believe this changes is not related to task

2024-05-02 13:53 UTC, andrii-hoienko commented on pom.xml
> +			<version>2.1.0</version>
Specify version as you did before using properties

2024-05-03 09:00 UTC, Nikname2303 commented on pom.xml
> +		</dependency>
For @ISBN annotation

2024-05-03 10:04 UTC, yevheniisynytsia approved these changes
Looks good, please update one small thing

2024-05-03 10:04 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @ISBN
null will work with this annotation. Please add `@NotNull`

2024-05-03 10:04 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @ISBN
https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ISBN.html

2024-05-03 10:25 UTC, merged