Book pagination
Nikname2303/book-store pull request #5
Opened 2024-05-02 13:53 UTC by Nikname2303

2024-05-02 19:40 UTC, fedaktaras approved these changes
Looks good to me

2024-05-03 15:09 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-03 15:09 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/controller/BookController.java
> +    @Operation(summary = "Delete book by id")
Please add description  to be consistent

2024-05-06 13:16 UTC, karma-o approved these changes
:+1:

2024-05-07 11:37 UTC, merged