Book security user
Nikname2303/book-store pull request #6
Opened 2024-05-07 11:33 UTC by Nikname2303

2024-05-08 13:41 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/annotation/FieldMatchesValidator.java
> +        fields = constraintAnnotation.value();
fields is not used

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/dto/UserRegistrationRequestDto.java
> +@FieldMatch({"password", "repeatPassword"})
No reason to define values, you don`t use them. Please implement annotation to make it work with any 2 fields

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/mapper/UserMapper.java
> +
```suggestion
```

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto requestDto) throws RegistrationException;
RegistrationException is unchecked, it is defined in signature?

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/impl/UserServiceImpl.java
> +        user.setLastName(requestDto.getLastName());
Is it possible to use userMapper?

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/03-create-users-table.yaml
```suggestion
      file: db/changelog/changes/03-create-users-table.yaml
      
```

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler({RegistrationException.class})
```suggestion
    @ExceptionHandler(RegistrationException.class)
```

2024-05-08 13:41 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/annotation/FieldMatch.java
> +
```suggestion
```

2024-05-08 13:41 UTC, andrii-hoienko commented on pom.xml
> +		</dependency>
This PR contains changes from 2 tasks, add User entity and Pagination, Sorting, Swagger. Please make PR only with relevant changes

2024-05-09 11:48 UTC, Nikname2303 commented
I fixed problem with previous commits, but with merge, so I still have history from previous PR. But files changes have only relevant changes. On QnA we discussed about that

2024-05-09 13:38 UTC, andrii-hoienko requested changes
Please read requirementsand comment cerafully

2024-05-09 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/annotation/FieldMatchesValidator.java
> +}
This still works only for 2 specific fields

2024-05-09 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
```suggestion
public class RegistrationException extends RuntimeException {
```

2024-05-09 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto requestDto) throws RegistrationException;
```suggestion
    UserResponseDto register(UserRegistrationRequestDto requestDto);
```

2024-05-09 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(userMapper.toModelFromRegisterDto(requestDto));
You should check is email valid

2024-05-13 12:37 UTC, andrii-hoienko requested changes
Good job!

2024-05-14 07:05 UTC, boroda4436 approved these changes

2024-05-14 07:06 UTC, merged