Added AuthenticationService, JwtAuthenticationFilter, JwtUtil, Authen…
Nikname2303/book-store pull request #8
Opened 2024-05-14 12:49 UTC by Nikname2303

…ticationController

2024-05-14 13:11 UTC, andrii-hoienko requested changes
Nice, left some minor comments

2024-05-14 13:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto request) {
```

2024-05-14 13:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Move to constants

2024-05-14 13:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Magic number

2024-05-15 10:41 UTC, vovasalyha approved these changes

2024-05-15 11:08 UTC, merged