Book security category
Nikname2303/book-store pull request #9
Opened 2024-05-16 13:42 UTC by Nikname2303

2024-05-17 09:06 UTC, AnyaRatusnyak commented on src/main/java/com/example/bookshop/dto/book/CreateBookRequestDto.java
Why don't you add categories? private Set<Long> categoryIds;

2024-05-17 09:16 UTC, AnyaRatusnyak commented on src/main/java/com/example/bookshop/mapper/BookMapper.java
I can't find method  set  categories from CreateBookRequestDto  to model book with categories

2024-05-17 09:21 UTC, AnyaRatusnyak approved these changes
Good job )

2024-05-17 13:54 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
Should work without ROLE_

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/dto/book/BookDtoWithoutCategoryIds.java
> +    private String coverImage;
What is the reason to validate it? It this class used as requestDto?

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/dto/category/CategoryRequestDto.java
> +    private Long id;
```suggestion
```

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/dto/category/CategoryRequestDto.java
> +    private String description;
Add max limit

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany(fetch = FetchType.LAZY)
```

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/CategoryService.java
> +    public List<BookResponseDto> getBooksByCategoryId(Long id);
```suggestion
    List<BootWithoutCategories> getBooksByCategoryId(Long id);
```

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
Please check if the entity exists before taking any actions

2024-05-17 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
>          Book book = bookMapper.toModel(requestDto);
You should check if book categories exist before saving

2024-05-20 09:49 UTC, yevheniisynytsia requested changes

2024-05-20 09:49 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
>      }
I think it is more 5xx kind of status

An Exception occurred and you don't have a method to handle it

2024-05-20 09:49 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +        }
Andrii meant to check if the category ids that you pass in the `CreateBookRequestDto` are present in your db.
For example I may pass id 93123928381293. What will happen here and what you'd expect such an app to behave?

Let's think how to do it properly. Tip: get all the needed categories in one call to db. And make an informative exception message for the case when there is no category with such id(s)

2024-05-20 09:49 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
are you able to get a book with its categories properly with `LAZY`? Have you tested it?

2024-05-21 09:39 UTC, yevheniisynytsia approved these changes

2024-05-21 09:39 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +                .toList();
I think `removeAll` instead of `iterating+contains `may work faster here

2024-05-21 10:40 UTC, merged